First build-able SkRuntimeEffect binding
initRuntimeEffect in main()

Needs a default sk_sp<SkRuntimeEffect> holder type for "RuntimeEffect"

Without this, the runtime error is:
    ImportError: generic_type: type "RuntimeEffect" does not have a non-default holder type while its base "SkRefCnt" does