m135: SkPDF::MakeDocument(SkWStream*) changed behavior, needed to be rewritten to give old behavior.
m135: Use the new built-in callback SkPDF::JPEG::MetadataWithCallbacks as default constructor for SkPDF::Metadata;
2nd part of SkPDF::MakeDocument() breakage.

m135: Fixes the 3rd SkPDF::MakeDocument(SkWStream*) constructor which uses DictToMetadata.

Fixes #310

The m135 release note is misleading. `SkPDF::MakeDocument(SkWStream*)` is not deprecated (works with warning
or works but not recommended for new code), but it now throws an error:

Python 3.13.2 (main, Feb  4 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import skia
... import pytest
...
>>> stream = skia.DynamicMemoryWStream()
>>> document = skia.PDF.MakeDocument(stream)
../../src/pdf/SkPDFDocument.cpp:713: fatal error: "Must set both a jpegDecoder and jpegEncoder to create PDFs"

Milestone 135
-------------
  * `SkPDF::MakeDocument(SkWStream*)` [one argument] has been deprecated and will be removed. This is because SkPDFMetdata has added 2 required fields `jpegDecoder` and `jpegEncoder`. In order to make a reasonable PDF, those must be supplied (using the two argument factory). To make these easier to supply `include/docs/SkPDFJpegHelpers.h` has been added, which will use Skia's built-in jpeg encoder and decoder.