Fixes gn building with newer gcc
Actual message:

FAILED: src/gn/desc_builder.o
g++ -MMD -MF src/gn/desc_builder.o.d -I../src -I. -Wno-deprecated-copy -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/gn/desc_builder.cc -o src/gn/desc_builder.o
../src/gn/desc_builder.cc: In member function ‘base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const Scope*)’:
../src/gn/desc_builder.cc:179:21: error: redundant move in return statement [-Werror=redundant-move]
  179 |     return std::move(res);
      |            ~~~~~~~~~^~~~~
../src/gn/desc_builder.cc:179:21: note: remove ‘std::move’ call
../src/gn/desc_builder.cc: In instantiation of ‘base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const std::vector<T>&) [with T = Value]’:
../src/gn/desc_builder.cc:193:27:   required from here
../src/gn/desc_builder.cc:170:25: error: redundant move in return statement [-Werror=redundant-move]
  170 |     return std::move(res);
      |                         ^
../src/gn/desc_builder.cc:170:25: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors